// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backup.sql

package sqlc

import (
	"context"
)

const softDeleteAllUserConnections = `-- name: SoftDeleteAllUserConnections :exec
UPDATE connections
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE workspace_id IN (
    SELECT id FROM workspaces WHERE user_id = $1 AND deleted_at IS NULL
)
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAllUserConnections(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, softDeleteAllUserConnections, userID)
	return err
}

const softDeleteAllUserData = `-- name: SoftDeleteAllUserData :exec
UPDATE saved_scripts
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAllUserData(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, softDeleteAllUserData, userID)
	return err
}

const softDeleteAllUserWorkspaces = `-- name: SoftDeleteAllUserWorkspaces :exec
UPDATE workspaces
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAllUserWorkspaces(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, softDeleteAllUserWorkspaces, userID)
	return err
}
