// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connections.sql

package sqlc

import (
	"context"
)

const createConnection = `-- name: CreateConnection :one
INSERT INTO connections (
    workspace_id,
    name,
    environment,
    driver,
    host,
    port,
    database_name,
    username,
    password_encrypted,
    ssl_mode
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, workspace_id, name, environment, driver, host, port, database_name, username, password_encrypted, ssl_mode, created_at, updated_at, deleted_at
`

type CreateConnectionParams struct {
	WorkspaceID       int64                 `json:"workspace_id"`
	Name              string                `json:"name"`
	Environment       ConnectionEnvironment `json:"environment"`
	Driver            ConnectionDriver      `json:"driver"`
	Host              string                `json:"host"`
	Port              int32                 `json:"port"`
	DatabaseName      string                `json:"database_name"`
	Username          *string               `json:"username"`
	PasswordEncrypted *string               `json:"password_encrypted"`
	SslMode           string                `json:"ssl_mode"`
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, createConnection,
		arg.WorkspaceID,
		arg.Name,
		arg.Environment,
		arg.Driver,
		arg.Host,
		arg.Port,
		arg.DatabaseName,
		arg.Username,
		arg.PasswordEncrypted,
		arg.SslMode,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Environment,
		&i.Driver,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.PasswordEncrypted,
		&i.SslMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getConnectionByID = `-- name: GetConnectionByID :one
SELECT id, workspace_id, name, environment, driver, host, port, database_name, username, password_encrypted, ssl_mode, created_at, updated_at, deleted_at
FROM connections
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetConnectionByID(ctx context.Context, id int64) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnectionByID, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Environment,
		&i.Driver,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.PasswordEncrypted,
		&i.SslMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listConnectionsByWorkspace = `-- name: ListConnectionsByWorkspace :many
SELECT id, workspace_id, name, environment, driver, host, port, database_name, username, password_encrypted, ssl_mode, created_at, updated_at, deleted_at
FROM connections
WHERE workspace_id = $1
  AND deleted_at IS NULL
ORDER BY environment, name
`

func (q *Queries) ListConnectionsByWorkspace(ctx context.Context, workspaceID int64) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnectionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Environment,
			&i.Driver,
			&i.Host,
			&i.Port,
			&i.DatabaseName,
			&i.Username,
			&i.PasswordEncrypted,
			&i.SslMode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteConnection = `-- name: SoftDeleteConnection :exec
UPDATE connections
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteConnection(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteConnection, id)
	return err
}
