// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ConnectionDriver string

const (
	ConnectionDriverPostgres ConnectionDriver = "postgres"
	ConnectionDriverMysql    ConnectionDriver = "mysql"
	ConnectionDriverSqlite   ConnectionDriver = "sqlite"
)

func (e *ConnectionDriver) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConnectionDriver(s)
	case string:
		*e = ConnectionDriver(s)
	default:
		return fmt.Errorf("unsupported scan type for ConnectionDriver: %T", src)
	}
	return nil
}

type NullConnectionDriver struct {
	ConnectionDriver ConnectionDriver `json:"connection_driver"`
	Valid            bool             `json:"valid"` // Valid is true if ConnectionDriver is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConnectionDriver) Scan(value interface{}) error {
	if value == nil {
		ns.ConnectionDriver, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConnectionDriver.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConnectionDriver) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConnectionDriver), nil
}

type ConnectionEnvironment string

const (
	ConnectionEnvironmentDevelopment ConnectionEnvironment = "development"
	ConnectionEnvironmentStaging     ConnectionEnvironment = "staging"
	ConnectionEnvironmentProduction  ConnectionEnvironment = "production"
)

func (e *ConnectionEnvironment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConnectionEnvironment(s)
	case string:
		*e = ConnectionEnvironment(s)
	default:
		return fmt.Errorf("unsupported scan type for ConnectionEnvironment: %T", src)
	}
	return nil
}

type NullConnectionEnvironment struct {
	ConnectionEnvironment ConnectionEnvironment `json:"connection_environment"`
	Valid                 bool                  `json:"valid"` // Valid is true if ConnectionEnvironment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConnectionEnvironment) Scan(value interface{}) error {
	if value == nil {
		ns.ConnectionEnvironment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConnectionEnvironment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConnectionEnvironment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConnectionEnvironment), nil
}

type Connection struct {
	ID                int64                 `json:"id"`
	WorkspaceID       int64                 `json:"workspace_id"`
	Name              string                `json:"name"`
	Environment       ConnectionEnvironment `json:"environment"`
	Driver            ConnectionDriver      `json:"driver"`
	Host              string                `json:"host"`
	Port              int32                 `json:"port"`
	DatabaseName      string                `json:"database_name"`
	Username          *string               `json:"username"`
	PasswordEncrypted *string               `json:"password_encrypted"`
	SslMode           string                `json:"ssl_mode"`
	CreatedAt         pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz    `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz    `json:"deleted_at"`
}

type SavedScript struct {
	ID           int64              `json:"id"`
	WorkspaceID  int64              `json:"workspace_id"`
	UserID       int64              `json:"user_id"`
	Title        string             `json:"title"`
	SqlText      string             `json:"sql_text"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	IsFavorite   bool               `json:"is_favorite"`
	FavoriteSort *int32             `json:"favorite_sort"`
}

type SavedScriptTag struct {
	ScriptID int64 `json:"script_id"`
	TagID    int64 `json:"tag_id"`
}

type ScriptTag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Workspace struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
