// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saved_scripts.sql

package sqlc

import (
	"context"
)

const createSavedScript = `-- name: CreateSavedScript :one
INSERT INTO saved_scripts (workspace_id, user_id, title, sql_text)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, user_id, title, sql_text, created_at, updated_at, deleted_at, is_favorite, favorite_sort
`

type CreateSavedScriptParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	UserID      int64  `json:"user_id"`
	Title       string `json:"title"`
	SqlText     string `json:"sql_text"`
}

func (q *Queries) CreateSavedScript(ctx context.Context, arg CreateSavedScriptParams) (SavedScript, error) {
	row := q.db.QueryRow(ctx, createSavedScript,
		arg.WorkspaceID,
		arg.UserID,
		arg.Title,
		arg.SqlText,
	)
	var i SavedScript
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Title,
		&i.SqlText,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsFavorite,
		&i.FavoriteSort,
	)
	return i, err
}

const deleteScriptTagsForScript = `-- name: DeleteScriptTagsForScript :exec
DELETE FROM saved_script_tags
WHERE script_id = $1
`

func (q *Queries) DeleteScriptTagsForScript(ctx context.Context, scriptID int64) error {
	_, err := q.db.Exec(ctx, deleteScriptTagsForScript, scriptID)
	return err
}

const getSavedScriptByID = `-- name: GetSavedScriptByID :one
SELECT id, workspace_id, user_id, title, sql_text, created_at, updated_at, deleted_at, is_favorite, favorite_sort
FROM saved_scripts
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetSavedScriptByID(ctx context.Context, id int64) (SavedScript, error) {
	row := q.db.QueryRow(ctx, getSavedScriptByID, id)
	var i SavedScript
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Title,
		&i.SqlText,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsFavorite,
		&i.FavoriteSort,
	)
	return i, err
}

const linkScriptTag = `-- name: LinkScriptTag :exec
INSERT INTO saved_script_tags (script_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkScriptTagParams struct {
	ScriptID int64 `json:"script_id"`
	TagID    int64 `json:"tag_id"`
}

func (q *Queries) LinkScriptTag(ctx context.Context, arg LinkScriptTagParams) error {
	_, err := q.db.Exec(ctx, linkScriptTag, arg.ScriptID, arg.TagID)
	return err
}

const listSavedScriptsByUser = `-- name: ListSavedScriptsByUser :many
SELECT s.id, s.workspace_id, s.user_id, s.title, s.sql_text, s.created_at, s.updated_at, s.deleted_at, s.is_favorite, s.favorite_sort
FROM saved_scripts s
INNER JOIN workspaces w ON w.id = s.workspace_id
WHERE w.user_id = $1
  AND s.deleted_at IS NULL
  AND w.deleted_at IS NULL
ORDER BY s.updated_at DESC
`

func (q *Queries) ListSavedScriptsByUser(ctx context.Context, userID int64) ([]SavedScript, error) {
	rows, err := q.db.Query(ctx, listSavedScriptsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedScript{}
	for rows.Next() {
		var i SavedScript
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Title,
			&i.SqlText,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsFavorite,
			&i.FavoriteSort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedScriptsByWorkspace = `-- name: ListSavedScriptsByWorkspace :many
SELECT id, workspace_id, user_id, title, sql_text, created_at, updated_at, deleted_at, is_favorite, favorite_sort
FROM saved_scripts
WHERE workspace_id = $1
  AND deleted_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListSavedScriptsByWorkspace(ctx context.Context, workspaceID int64) ([]SavedScript, error) {
	rows, err := q.db.Query(ctx, listSavedScriptsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedScript{}
	for rows.Next() {
		var i SavedScript
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Title,
			&i.SqlText,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsFavorite,
			&i.FavoriteSort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForScript = `-- name: ListTagsForScript :many
SELECT t.id, t.name
FROM script_tags t
INNER JOIN saved_script_tags st ON st.tag_id = t.id
WHERE st.script_id = $1
ORDER BY t.name
`

func (q *Queries) ListTagsForScript(ctx context.Context, scriptID int64) ([]ScriptTag, error) {
	rows, err := q.db.Query(ctx, listTagsForScript, scriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScriptTag{}
	for rows.Next() {
		var i ScriptTag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxFavoriteSortForUser = `-- name: MaxFavoriteSortForUser :one
SELECT COALESCE(MAX(favorite_sort), 0)::int AS max_sort
FROM saved_scripts
WHERE user_id = $1
  AND is_favorite = TRUE
  AND deleted_at IS NULL
`

func (q *Queries) MaxFavoriteSortForUser(ctx context.Context, userID int64) (int32, error) {
	row := q.db.QueryRow(ctx, maxFavoriteSortForUser, userID)
	var max_sort int32
	err := row.Scan(&max_sort)
	return max_sort, err
}

const setScriptFavorite = `-- name: SetScriptFavorite :one
UPDATE saved_scripts
SET is_favorite = $2,
    favorite_sort = $3,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, workspace_id, user_id, title, sql_text, created_at, updated_at, deleted_at, is_favorite, favorite_sort
`

type SetScriptFavoriteParams struct {
	ID           int64  `json:"id"`
	IsFavorite   bool   `json:"is_favorite"`
	FavoriteSort *int32 `json:"favorite_sort"`
}

func (q *Queries) SetScriptFavorite(ctx context.Context, arg SetScriptFavoriteParams) (SavedScript, error) {
	row := q.db.QueryRow(ctx, setScriptFavorite, arg.ID, arg.IsFavorite, arg.FavoriteSort)
	var i SavedScript
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Title,
		&i.SqlText,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsFavorite,
		&i.FavoriteSort,
	)
	return i, err
}

const softDeleteSavedScript = `-- name: SoftDeleteSavedScript :exec
UPDATE saved_scripts
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSavedScript(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteSavedScript, id)
	return err
}

const updateSavedScript = `-- name: UpdateSavedScript :one
UPDATE saved_scripts
SET title = $2,
    sql_text = $3,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, workspace_id, user_id, title, sql_text, created_at, updated_at, deleted_at, is_favorite, favorite_sort
`

type UpdateSavedScriptParams struct {
	ID      int64  `json:"id"`
	Title   string `json:"title"`
	SqlText string `json:"sql_text"`
}

func (q *Queries) UpdateSavedScript(ctx context.Context, arg UpdateSavedScriptParams) (SavedScript, error) {
	row := q.db.QueryRow(ctx, updateSavedScript, arg.ID, arg.Title, arg.SqlText)
	var i SavedScript
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Title,
		&i.SqlText,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsFavorite,
		&i.FavoriteSort,
	)
	return i, err
}

const upsertScriptTag = `-- name: UpsertScriptTag :one
INSERT INTO script_tags (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) UpsertScriptTag(ctx context.Context, name string) (ScriptTag, error) {
	row := q.db.QueryRow(ctx, upsertScriptTag, name)
	var i ScriptTag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
