// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package sqlc

import (
	"context"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at, updated_at, deleted_at
`

type CreateWorkspaceParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.UserID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, user_id, name, created_at, updated_at, deleted_at
FROM workspaces
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT id, user_id, name, created_at, updated_at, deleted_at
FROM workspaces
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userID int64) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByUserSearch = `-- name: ListWorkspacesByUserSearch :many
SELECT id, user_id, name, created_at, updated_at, deleted_at
FROM workspaces
WHERE user_id = $1
  AND deleted_at IS NULL
  AND name ILIKE '%' || $2 || '%'
ORDER BY name
LIMIT 50
`

type ListWorkspacesByUserSearchParams struct {
	UserID int64   `json:"user_id"`
	Search *string `json:"search"`
}

func (q *Queries) ListWorkspacesByUserSearch(ctx context.Context, arg ListWorkspacesByUserSearchParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUserSearch, arg.UserID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkspace = `-- name: SoftDeleteWorkspace :exec
UPDATE workspaces
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkspace(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteWorkspace, id)
	return err
}

const updateWorkspaceName = `-- name: UpdateWorkspaceName :one
UPDATE workspaces
SET name = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, user_id, name, created_at, updated_at, deleted_at
`

type UpdateWorkspaceNameParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateWorkspaceName(ctx context.Context, arg UpdateWorkspaceNameParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceName, arg.ID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
